language: node_js
node_js:
- '8'
- '9'
- stable
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: mKlSQ9puIbQbTNiewxa6NzfWyq8ztNXw9q4fnezRBU4L232Kp52p/q402Pirjh3PAXMAdAUcfmbop/aIxuk1i7B2wKWBXw1xbj+jBwxG4Ler2aaxHLx6p6MSVGcOgNOapOaY3Jve4fCiBX9Bq9v6qxkodHdMVHX2lZYnlOfvog/dDzvRynbWRSARenBZNpUcmbhHIB2hVb4+q1Q5+/xB5TYrRl6GIksay32oVD15d2nHn7TjtrEMk9MgttqMH7xSNgyEGysBGaAd63emovZ8C9ZSVT+bQe4grICnfcZ8KT1kQV2gN0qLXL5R9ryd7cZVOPG8y24oA5AcwLFfhV/AKFeLhoYIhJLl38/pzd1abjJyiemeleLgs8IWsI5BQbRnMnTNjwYgZn7b+5r2qqJGx/p+pqjc9ZKrV0L/+8PwUpTAM/UwUodQLYV3s9a7RHX/i2R42BoXNemL7ykmjesnAYS51dltXsvNx1jbRkh3i9vdwiixK+BrzD8/X8H9NxLFM1CCL27cjb8AOXfh7xwzaGse9hWVa7aMqYboymzOA5oJNaknOSj0zOLkPe6k3wXNlnAPfhedv3nFuN4Jlsyb3R/qy6ujNo3FCAD7AzIJjK4O2+Mr77NX10MbE1c6+wmKF9kQda+vTvKmh3cc6uPW6OgY/MwDG3lQOiqIGWBSqpI=
  on:
    tags: true
    repo: taskcluster/taskcluster-lib-log
